apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ehn9snwas-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bd58ffddf5.7y7x.p3.openshiftapps.com/rhtap/rhtap-qe:f6d444227ebc0b33e21bb5bd1915be143f8aae5e@sha256:8a310155f1706bd873cad8b884d897130d69e3f0b3069f557f53d0224f02937f
          name: container-image
